server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms1-pos-processor
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cordillera_pos}?useSSL=false&allowPublicKeyRetrieval=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  rabbitmq:
    queue:
      pos: ${RABBITMQ_QUEUE_POS:q.pos.deviamserver}
  orquestador:
    url: ${ORQUESTADOR_URL:http://localhost:8080/api/v1/pos}

resilience4j:
  circuitbreaker:
    instances:
      orquestadorCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
